#hdd_path = "/run/media/ax/sg8"
hdd_path = "/home/ax"

#archive_dir = "/run/media/ax/sg8/manual-backups/backup-home"
archive_dir = "/home/ax/0-archive-dir/"

#dirs_to_backup = [
#    ".config/",
#    ".ssh/",
#    "MEGA/",
#    "my/",
#    "sync/",
#]

dirs_to_backup = [
    ".ssh/",
    "Documents",
    "wuffel",
    "puhpuh",
]

