#+TITLE: My fish config
#+AUTHOR: Arthur Fleck
#+DESCRIPTION: AF's personal fish config.
#+STARTUP: showeverything
#+OPTIONS: toc:3
#+PROPERTY: header-args:shell :tangle config.fish

* ToC :toc:
- [[#interactive][interactive]]
- [[#homebrew][homebrew]]
- [[#abbr][abbr]]
  - [[#cd][cd]]
  - [[#git][git]]
  - [[#heavy-hitters][heavy hitters]]
  - [[#medium-ones][medium ones]]
  - [[#rsync][(r)sync]]
  - [[#maybe-remove-those][maybe remove those]]
  - [[#misc][misc]]
- [[#alias][alias]]
- [[#export][export]]
  - [[#editor--visual][EDITOR / VISUAL]]
  - [[#terminal][TERMINAL]]
- [[#stuff-that-should-be-at-the-end][stuff that should be at the end]]
  - [[#starship][starship]]

* interactive
#+begin_src shell
if status is-interactive
    # Commands to run in interactive sessions can go here
end
#+end_src

* homebrew
I think this has to be at/near the top of the actual config file.
#+begin_src shell
eval (/home/linuxbrew/.linuxbrew/bin/brew shellenv)
#+end_src

* abbr
** cd
#+begin_src shell
abbr -a cda 'cd /Volumes/AppleEnc'
abbr -a cdc 'cd ~/code'
abbr -a cdo 'cd ~/obsidian-vault'
abbr -a cdg 'cd ~/code/golang/'
abbr -a cdi 'cd "/Users/ax/Library/Mobile Documents/com~apple~CloudDocs/"'
abbr -a cdM 'cd ~/MEGAsync/'
abbr -a cdm 'cd /media/ax'
abbr -a cdp 'cd ~/code/python/'
abbr -a cdr 'cd ~/code/rust'
abbr -a cdt 'cd /Volumes/TimeMachine/'
abbr -a cdb 'cd /Volumes/Blackbeard5'
abbr -a cdj "cd ~/code/clojure"

abbr -a db 'cd ~/Dropbox'
abbr -a dl 'cd ~/Downloads'
abbr -a dot 'cd ~/.config'
abbr -a dt 'cd ~/Desktop/'
#+end_src

** git 
#+begin_src shell
abbr -a ga 'git add'
abbr -a gb 'git branch'
abbr -a gc 'git commit -am'
abbr -a gca 'git commit --amend --no-edit'
abbr -a gcm 'git checkout main'
abbr -a gco 'git checkout'
abbr -a gd 'git diff'
abbr -a gin 'clear && git status && echo && git log --oneline -10 && echo && git branch && echo && tokei src/'

abbr -a gitinfo 'git config --get user.name && git config --get user.email'
abbr -a gl 'git log --oneline'
abbr -a gr 'git restore'
abbr -a gs 'git status'
abbr -a gms 'git merge --squash'
#+end_src

** heavy hitters
abbrs that I use very often

#+begin_src shell
abbr -a gi 'grep -i'
abbr -a hg 'history | grep -i'
abbr -a lg 'll | grep -i'
abbr -a lt 'll -t'
# by default, when in nnn, `e` opens a file with $VISUAL
abbr -a n "VISUAL='emacsclient -t' nnn"
abbr -a o. 'open .'
abbr -a rd 'rm -rf'
abbr -a pwdc 'pwd | xclip -selection clipboard'

abbr -a cgi 'cargo install --path .'
abbr -a cgr 'cargo run'
abbr -a cgt 'cargo test'
abbr -a cg cargo

abbr -a fd fdfind
abbr -a l "licht"
abbr -a str "cat ~/backup/streams.md"
abbr -a pnc "protonvpn-cli ks --off && protonvpn-cli ks --permanent && protonvpn-cli c --protocol tcp --fastest"

abbr -a cgc cargo check
abbr -a cgb 'cargo build'
abbr -a rl 'RUST_LOG=debug'
abbr -a s "strava-rs"
abbr -a st "strava-rs tui"

abbr -a i3t i3timer
abbr -a wt wttr
abbr -a ebands "e $HOME/.metal/bands.csv"


abbr -a bi 'brew info'
abbr -a bin 'brew install'
abbr -a bs 'brew search'
abbr -a ssa 'shasum --algorithm 256'
abbr -a ssc 'shasum --check'
abbr -a tl 'tree -L'
abbr -a todo 'rg -i todo --stats'

abbr -a up 'sudo apt update && sudo apt upgrade'
abbr -a upb 'brew update && brew upgrade'
abbr -a rc rclone
abbr -a el 'eza -l --group-directories-first --icons'
#+end_src

** medium ones
Not used often, but very useful.

#+begin_src shell
# official example:                     ffmpeg                 -i input.wav -codec:a libmp3lame -qscale:a 2 output.mp3
abbr -a flac2mp3 'fdfind -e flac --exec ffmpeg -loglevel error -i {} -codec:a libmp3lame -qscale:a 1 {.}.mp3'

abbr -a vd vimdiff
#+end_src

** (r)sync
#+begin_src shell
abbr -a syncmoto "rsync -ahvP --stats '/media/ax/wd2b/0-localsync/mukke/' '/run/user/1000/gvfs/mtp:host=motorola_moto_g54_5G_ZY22HWD8XQ/Internal shared storage/Music/mukke/' --delete --omit-dir-times --no-perms --inplace --size-only --ignore-existing -n"


abbr -a syncmov2 'rclone copy --progress /Volumes/Blackbeard5/media/movies/ sgefoo:movies/ -n'
abbr -a sync-local-only 'rsync -ahvP --delete --stats /Volumes/Blackbeard5/0-localsync/ /Volumes/AppleEnc/0-localsync/ -n'

abbr -a forget 'restic -r ~/MEGAsync/linux-repo/ forget --keep-weekly 52'
abbr -a rsn 'restic -r ~/MEGAsync/linux-repo/ snapshots'
#+end_src

** maybe remove those
#+begin_src shell
abbr -a fconf "hx ~/.config/fish/config.fish"
abbr -a es "exercism submit"
abbr -a sync-backup "rclone copy --progress /Volumes/Blackbeard5/0-localsync/backup/ b2e:backup/ -n"
abbr -a nt 'ntfy-cli -@ "test" -t "NTFY" -m "'

abbr -a ser 'xdg-open ~/Documents/serien2020.ods'
abbr -a cm chezmoi
abbr -a xo "xdg-open"
abbr -a rgi 'rg -iN "'
abbr -a sup "strava-rs update"
abbr -a cs "sudo cryptsetup"

abbr -a bt 'rclone tree b2e:'
abbr -a ce 'crontab -e'
abbr -a c clear

abbr -a rcp 'rclone copy --progress'
abbr -a rct 'rclone tree --level 2'

abbr -a sync-music-before 'rsync -ahv --delete --progress --stats /Volumes/AppleEnc/music2k/0music-before-import/Music/ /Users/ax/Music/Music/ -n'
abbr -a syncmov 'rclone copy --progress /Volumes/Blackbeard5/media/movies-glacier-sync/ sge:mov -n'
abbr -a syncmusicb2e 'rclone copy --progress /Volumes/Blackbeard5/0-localsync/music2k/ b2e:music2k/ -n'
abbr -a synctv 'rclone copy --progress /Volumes/Blackbeard5/media/tvshows-glacier-sync/ sge3000:tv -n'
abbr -a synctv2 'rclone copy --progress /Volumes/Blackbeard5/tv2/ sgefoo:tv2/ -n'

#+end_src

** misc
#+begin_src shell

set -g fish_user_paths "/usr/local/sbin" $fish_user_paths
# Color scheme for oh-my-fish theme "bobthefish"
set -g theme_color_scheme "nord"

# --export -x is the same
set -Ux RESTIC_PASSWORD_FILE "/home/ax/.restic-std"


#+end_src

* alias
#+begin_src shell
alias nf rnf

# when changing between abbr and alias, remove entry from `fish_variables` accordingly 
#abbr -a em 'emacsclient -t'
alias e "emacsclient -t" 
#+end_src

* export
** EDITOR / VISUAL
#+begin_src shell
export ALTERNATE_EDITOR=""
export EDITOR="emacsclient -t"                  # $EDITOR opens in terminal
export VISUAL="emacsclient -c -a emacs"         # $VISUAL opens in GUI mode
#+end_src

** TERMINAL
#+begin_src shell
export TERMINAL='kitty'
#+end_src

* stuff that should be at the end
#+begin_src shell

# TODO still relevant?
source ~/.local/share/icons-in-terminal/icons.fish

source ~/.config/fish/nnn.fish
## Stuff that should be at the end
zoxide init fish | source

#+end_src

** starship
From the docs:
Add the following to the end of ~/.config/fish/config.fish:
#+begin_src shell
starship init fish | source
#+end_src

Why do/did I have this?
# source (/home/linuxbrew/.linuxbrew/bin/starship init fish --print-full-init | psub)

